/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package optimize;
import org.lwjgl.glfw.GLFW;

public class App {
    public static void main(String[] args) {
        Game g = new Game();
        g.init();
        g.Run();
        }
}
